### INDEX cards

GET http://localhost:3000/cards
Authorization: Bearer 
Content-Type: application/json

### SHOW cards

GET http://localhost:3000/cards/:id
Authorization: Bearer 
Content-Type: application/json

### CREATE cards

POST http://localhost:3000/cards
Authorization: Bearer 
Content-Type: application/json

{
  "name": "Test name",
  "month": "test@test.com",
  "day": "password",
  "time": "password",
  "privacy": "",
  "course_id": "",
  "user_id": ""
}


### UPDATE cards

PATCH http://localhost:3000/cards/:id
Authorization: Bearer 
Content-Type: application/json

### DESTROY cards

DELETE http://localhost:3000/cards/:id
Authorization: Bearer 
Content-Type: application/json