### INDEX courses

GET http://localhost:3000/courses
Content-Type: application/json

### SHOW courses

GET http://localhost:3000/courses/2
Content-Type: application/json

### CREATE courses

POST http://localhost:3000/courses
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzg5MDI0ODN9.aH1A2kdWZIs2Cx7yxQ6c3CFAh95w-TNkA0rX35jjpfQ
Content-Type: application/json

{
  "name": "Test",
  "address": "test",
  "hole_count": 18,
  "course_par": 54,
  "rating": 3,
  "image": "https://www.anytimefitness.com/wp-content/uploads/2020/09/AdobeStock_86831923-1024x576.webp"
}

### UPDATE courses

PATCH http://localhost:3000/courses/2
Authorization: Bearer 
Content-Type: application/json

{
  "name": "Test 2"
}

### DESTROY courses

DELETE http://localhost:3000/courses/3
Authorization: Bearer 
Content-Type: application/json