### INDEX users

GET http://localhost:3000/users
Authorization: Bearer 
Content-Type: application/json

### SHOW users

GET http://localhost:3000/users/6
Authorization: Bearer 
Content-Type: application/json

### HOME user

GET http://localhost:3000/userhome/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Mzk1MDQ1ODJ9.bKgMlRDJYms2fAekDyxsNWZoOHHh9AmoTvWwCtAYKfI
Content-Type: application/json

### CREATE users

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "r@r.com",
  "urer_name": "r",
  "password": "password",
  "password_confirmation": "password",
  "admin": true
}

### UPDATE users

PATCH http://localhost:3000/users/6
Authorization: Bearer 
Content-Type: application/json



### DESTROY users

DELETE http://localhost:3000/users/6
Authorization: Bearer 
Content-Type: application/json

### SESSIONS create
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "m@m.com",
  "password": "password"
}